cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace = 'store')),    # namespace 
    path('cart/', include('cart.urls', namespace= 'cart')),   # path đến cái page cart
    path('account/', include('account.urls', namespace= 'account')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace= 'payment')),
    path('__debug__/', include(debug_toolbar.urls)),
]
# Đảm bảo Django xử lý các tệp media trong chế độ phát triển
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name= 'store_home'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
    path('searchType/<slug:type_slug>/', views.type_list, name='type_list'),
    path('searchItem/', views.search_item, name='search'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, get_object_or_404
from store.models import Product
from .cart import Cart
from django.http import JsonResponse

# Create your views here.

def cart_summary(request):
    cart = Cart(request)     # ini object => cart.py
    return render(request, 'cart/summary.html', {'cart': cart})

def cart_add(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id= product_id)
        cart.add(product= product, qty= product_qty)
        cartqty = cart.__len__()
        response = JsonResponse({'qty': cartqty})   # lúc đầu để là 'qty': product_qty nên chỉ trả về qty của 1 product
        return response

def cart_delete(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        cart.delete(product= product_id)
        cartqty = cart.__len__()  # tổng số item trong cart(sau khi delete do có lệnh delete phía trên rồi)
        carttotal = cart.get_total_price() # tổng tiền(sau khi delete)
        response = JsonResponse({'qty': cartqty, 'subtotal': carttotal})
        return response      # phải có return response ko là n ko cập nhật gì hết

def cart_update(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        cart.update(product= product_id, qty= product_qty)
        cartqty = cart.__len__()  # tổng số item trong cart(sau khi delete do có lệnh delete phía trên rồi)
        carttotal = cart.get_subtotal_price() # tổng tiền(sau khi delete)
        response = JsonResponse({'qty': cartqty, 'subtotal': carttotal})
        return response      # phải có return response ko là n ko cập nhật gì hết

templates/cart/summary.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Cart Summary{%endblock %}
{% block content %}

<div  class="container">
  <div  class="row g-3">
    {% if cart|length == 0 %}
    <div class="col-12">Your cart is empty <a href="{% url 'store:store_home' %}">Shop</a></div>
    {% else %}
    <div class="col-12 bg-light p-3 d-flex justify-content-between">
      <div class="d-flex d-flex-inline">
        <div class="pe-3">Order</div>
        <div class="dropdown">
          <a class="text-reset text-decoration-none dropdown-toggle" href="#" role="link" id="dropdownLink"
            data-bs-toggle="dropdown" aria-expanded="false">
            Shipping options
            <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor"
              class="bi bi-chevron-down" viewBox="0 0 16 16">
              <path fill-rule="evenodd"
                d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" />
            </svg>
          </a>
          <ul class="dropdown-menu" aria-labelledby="dropdownLink">
            <li class="item small">Next day delivery</li>
            <li class="item small">Premimum delivery</li>
          </ul>
        </div>
      </div>
      <div class="text-end">
        <div class="">Sub Total: <span class="fw-bold">£</span>
          <div id="subtotal" class="d-inline-flex fw-bold">{{cart.get_subtotal_price}}</div>
        </div>
        <div id="">Shipping <span class="small">(Next day delivery)</span>: <span class="fw-bold">£11.50</span></div>
        <div class="pt-2">Total to pay: <span class="fw-bold h5">£</span><span id="total"
            class="fw-bold h5">{{cart.get_total_price}}</span></div>
      </div>
    </div>
    <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
      <div class="d-grid gap-2 ">
        <a role="button" href="{% url "payment:cart" %}" class="btn btn-black fw-bold btn-mgl" type="button">Checkout</a>
        <button class="btn btn-light btn-mgl" type="button">Save for later</button>
      </div>
    </div>
    <div class="col-md-7 col-lg-8 p-0" id="product-cart">
      {% for item in cart %}
      {% with product=item.product %}
      <div class="card mb-3 border-0 product-item" data-index="{{product.id}}">
        <div class="row g-0">
          <div class="col-md-2 d-none d-md-block">
            {% for image in product.product_image.all %}
              {% if image.is_feature%}   <!--lấy ảnh chính thôi-->
              <img class="img-fluid" alt="Responsive image" src="{{ image.image.url }}"
                alt="{{ image.image.alt_text }}">
              {% endif %}
              {% endfor %}
          </div>
          <div class="col-md-10 ps-md-3">
            <div class="card-body p-1">
              <a class="text-decoration-none text-reset" href="{{item.product.get_absolute_url}}">
                <p class="card-text pb-3">{{product.title}}</p>
              </a>
              <label for="select">Qty</label>
              <select id="select{{product.id}}" style="width:50px;height:31px;">
                <option value="" selected disabled hidden>{{item.qty}}</option>
                <option value="">1</option>
                <option value="">2</option>
                <option value="">3</option>
                <option value="">4</option>
              </select>
              <a type="button" id="update-button" data-index="{{product.id}}"
                class="update-button text-decoration-none small ps-3">
                <svg xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 50 50" width="20px" height="20px"><path d="M 25 2 A 2.0002 2.0002 0 1 0 25 6 C 35.517124 6 44 14.482876 44 25 C 44 35.517124 35.517124 44 25 44 C 14.482876 44 6 35.517124 6 25 C 6 19.524201 8.3080175 14.608106 12 11.144531 L 12 15 A 2.0002 2.0002 0 1 0 16 15 L 16 4 L 5 4 A 2.0002 2.0002 0 1 0 5 8 L 9.5253906 8 C 4.9067015 12.20948 2 18.272325 2 25 C 2 37.678876 12.321124 48 25 48 C 37.678876 48 48 37.678876 48 25 C 48 12.321124 37.678876 2 25 2 z"/>
                </svg>
              </a>
              <a type="button" id="delete-button" data-index="{{product.id}}"
                class="delete-button text-decoration-none small">
                <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="20px" height="20px" viewBox="0 0 24 24">
                  <path d="M 10 2 L 9 3 L 4 3 L 4 5 L 5 5 L 5 20 C 5 20.522222 5.1913289 21.05461 5.5683594 21.431641 C 5.9453899 21.808671 6.4777778 22 7 22 L 17 22 C 17.522222 22 18.05461 21.808671 18.431641 21.431641 C 18.808671 21.05461 19 20.522222 19 20 L 19 5 L 20 5 L 20 3 L 15 3 L 14 2 L 10 2 z M 7 5 L 17 5 L 17 20 L 7 20 L 7 5 z M 9 7 L 9 18 L 11 18 L 11 7 L 9 7 z M 13 7 L 13 18 L 15 18 L 15 7 L 13 7 z"></path>
                  </svg>
              </a>
              
            </div>
          </div>
        </div>
      </div>
      {% endwith %}
      {% endfor %}
    </div>
    {% endif %}
  </div>
</div>
      <script>
        $(document).on('click', '.delete-button', function(e) {    
            e.preventDefault();
            var prodid = $(this).data('index');    // productid, id của sp t delete
            $.ajax({
                type: 'POST',
                url: '{% url "cart:cart_delete" %}',
                data: {
                    productid: $(this).data('index'),
                    csrfmiddlewaretoken: "{{csrf_token}}",
                    action: 'post'
                },
                success: function (json) {  // cái này là data response từ cái JSON_RESPONSE, cơ bản là update giao diện luôn, ko cần refresh
                    $('.product-item[data-index="' + prodid + '"]').remove(); // xóa đi cái product item với data-index là productid tương ứng

                    if(json.qty == 0){
                      total = 0
                      subtotal = 0
                    }
                    else{
                      total = (parseFloat(json.subtotal) + 11.50).toFixed(2);
                      subtotal = json.subtotal
                    }
                    document.getElementById('subtotal').innerHTML = json.subtotal
                    document.getElementById("cart-qty").innerHTML = json.qty
                    document.getElementById("total").innerHTML = total;
                },
                error: function (xhr, errmsg, err) {
    
                }
            });
        });
    // Update Item
        $(document).on('click', '.update-button', function (e) {
        e.preventDefault();
        var prodid = $(this).data('index');
        $.ajax({
            type: 'POST',
            url: '{% url "cart:cart_update" %}',
            data: {
                productid: $(this).data('index'),
                productqty: $('#select' + prodid + ' option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
        },
        success: function (json) {
            document.getElementById("cart-qty").innerHTML = json.qty
            document.getElementById("subtotal").innerHTML = json.subtotal
            total = (parseFloat(json.subtotal) + 11.50).toFixed(2);
            document.getElementById("total").innerHTML = total;
        },
        error: function (xhr, errmsg, err) {}
        });
    })
    </script>
{% endblock %}