account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', views.logout_user, name='logout'),   # dùng auth view bị lỗi, ko dùng được
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset/password_reset_form.html",  # dẫn đến chỗ reset password, chỗ đó p confirm email 
                                                                 success_url='password_reset_email_confirm',  # confirm xong email thì dẫn đến chỗ confirm 
                                                                 email_template_name='account/password_reset/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset/password_reset_confirm.html', # link đến chỗ reset password
                                                                                                success_url='password_reset_complete/', # reset xong thì đến chỗ này
                                                                                                form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_done'), # đây là sau khi cf email xong thì dẫn đến chỗ này để tbao đã thành công
    path('password_reset_confirm/<uidb64>/password_reset_complete/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_complete'),  # sau khi reset password xong thì dẫn đến chỗ này để tbao đã reset thành công
    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),    # dẫn người dùng đến dashboard
    path('orders/', views.view_orders, name='orders'),    # dẫn người dùng đến dashboard
    path('profile/edit/', views.edit_details, name='edit_details'),  # dẫn đến chỗ edit profile người dùng
    path('profile/delete_user/', views.delete_user, name='delete_user'),   # dẫn đến chỗ delele user
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/dashboard/delete_confirm.html"), name='delete_confirmation'),
    # Address
    path("addresses/", views.view_address, name="addresses"),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),
    # Wishlist
    path("wishlist", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"),
    path('submit-problem/', views.submit_problem, name='submit_problem'),
    path('submit-review/', views.submit_review, name='submit_review'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update')
]

payment/urls.py
from django.urls import path

from . import views

app_name = 'payment'

urlpatterns = [
    path('', views.CartView, name = 'cart'),
    path('orderplaced/', views.order_placed, name='order_placed'),
    path('webhook/', views.stripe_webhook),
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
import stripe
import json
import os
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from cart.cart import Cart
from django.views.decorators.csrf import csrf_exempt
from django.http.response import HttpResponse
from orders.views import payment_confirmation
from django.views.generic.base import TemplateView
from django.conf import settings
# Create your views here.


def order_placed(request):
    cart = Cart(request)
    cart.clear()    # khi order xong thì xóa các item trong cart đi
    return render(request, 'payment/orderplaced.html')


class Error(TemplateView):
    template_name = 'payment/error.html'
    

@login_required
def CartView(request):
    cart = Cart(request)
    total = str(cart.get_total_price())
    total = total.replace('.', '')
    total = int(total)
    stripe.api_key = settings.STRIPE_SECRET_KEY
    intent = stripe.PaymentIntent.create(    # tạo 1 paymentIntent để thu tiền
        amount=total,    # số tiền
        currency='gbp',   # mã tiền tệ, gbp là bảng Anh
        metadata={'userid': request.user.id}  # lấy id xem thằng nào là thằng pay(metadata là thông tin bổ sung vào)
    )
    return render(request, 'payment/payment_form.html', {'client_secret': intent.client_secret, 
                                                            'STRIPE_PUBLISHABLE_KEY': os.environ.get('STRIPE_PUBLISHABLE_KEY')})

# nhận và xử lí các sự kiện từ Stripe
@csrf_exempt   #  Bỏ qua kiểm tra CSRF (Cross-Site Request Forgery) cho hàm này vì webhook là một endpoint mà Stripe sẽ gửi yêu cầu POST đến từ bên ngoài.
def stripe_webhook(request):  # Định nghĩa hàm stripe_webhook nhận đối tượng request từ Django.
    payload = request.body  # Lấy nội dung của yêu cầu POST từ Stripe
    event = None

    try:
        event = stripe.Event.construct_from(
            json.loads(payload), stripe.api_key   # Dùng Stripe SDK để xây dựng một đối tượng sự kiện từ JSON payload và khóa API của Stripe.
        )
    except ValueError as e:
        print(e)
        return HttpResponse(status=400)

    # Handle the event
    if event.type == 'payment_intent.succeeded':   # khi thanh toán thành công
        print('gui di')
        payment_confirmation(event.data.object.client_secret)

    else:
        print('Unhandled event type {}'.format(event.type))   # in ra loại sự kiện không được xử lí

    return HttpResponse(status=200) 

templates/payment/error.html
{% extends "./sub_base.html" %}
{% load static %}
{% block title %}Error{% endblock %}
{% block content %}

<div class="container">
  <div class="col-12 col-lg-6">
    <h3 class="mb-4">Order Error</h3>
    <p>Please contact our customer support team</p>
    <a href="{% url "account:dashboard" %}">Dashboard</a>
  </div>     
</div>

{% endblock %}

templates/payment/orderplaced.html
{% extends "./sub_base.html" %}
{% load static %}
{% block title %}Order Placed{% endblock %}
{% block content %}

<div class="container">
  <div class="col-12 col-lg-6">
    <h3 class="mb-4">Order has been placed</h3>
    <p>Check your email for confirmation</p>
    <a href="{% url "account:orders" %}">See orders</a>
  </div>     
</div>

{% endblock %}

templates/payment/payment_form.html
{% extends "./sub_base.html" %}
{% load static %}
{% block title %}Make Payment{% endblock %}

{% block sub_content %}

<form id="payment-form">
  <h3 class="mb-3">Billing address</h3>
  <!-- Error messages in this element -->
  <div id="card-errors" class="a" role="alert"></div>
  <div class="row g-3">
    <div class="col-sm-7">
      <label for="firstName" class="form-label">Customer Name</label>
      <input type="text" class="form-control" id="custName" placeholder="" required>
      <div class="invalid-feedback">
        Valid first name is required.
      </div>
    </div>
    <div class="col-12">
      <label for="email" class="form-label">Email <span class="text-muted">(Optional)</span></label>
      <input type="email" class="form-control" id="email" placeholder="you@example.com">
      <div class="invalid-feedback">
        Please enter a valid email address for shipping updates.
      </div>
    </div>
    <div class="col-12">
      <label for="address" class="form-label">Address</label>
      <input type="text" class="form-control" id="custAdd" placeholder="1234 Main St" required>
      <div class="invalid-feedback">
        Please enter your shipping address.
      </div>
    </div>
    <div class="col-12">
      <label for="address2" class="form-label">Address 2 <span class="text-muted">(Optional)</span></label>
      <input type="text" class="form-control" id="custAdd2" placeholder="Apartment or suite">
    </div>
    <div class="col-md-5">
      <label for="country" class="form-label">Country</label>
      <select class="form-select" id="country" required>
        <option value="">Choose...</option>
        <option>United States</option>
      </select>
      <div class="invalid-feedback">
        Please select a valid country.
      </div>
    </div>
    <div class="col-md-4">
      <label for="state" class="form-label">State</label>
      <select class="form-select" id="state" required>
        <option value="">Choose...</option>
        <option>California</option>
      </select>
      <div class="invalid-feedback">
        Please provide a valid state.
      </div>
    </div>
    <div class="col-md-3">
      <label for="Postcode" class="form-label">Postcode</label>
      <input type="text" class="form-control" id="postCode" placeholder="" required>
      <div class="invalid-feedback">
        Zip code required.
      </div>
    </div>
  </div>
  <hr class="my-4">
  <h4 class="mb-3">Payment</h4>
  <label for="card-element">Credit or debit card</label>
  <div id="card-element" class="form-control form-control-payment">
    <!-- Payment elements will appear here -->
  </div>
  <hr class="my-4">
  <button id="submit" class="btn btn-primary w-100 fw-bold" data-secret="{{ client_secret }}">Pay</button>
</form>

<script>
  var STRIPE_PUBLISHABLE_KEY = '{{STRIPE_PUBLISHABLE_KEY}}'
  var CSRF_TOKEN = '{{ csrf_token }}';
</script>
<script src="https://js.stripe.com/v3/"></script> <!--set up payment secure-->
<script src="{% static 'payment/index.js' %}" data-rel-js></script>
<script src="{% static 'core/scripts/base.js' %}" data-rel-js></script>

{% endblock %}

templates/payment/sub_base.html
{% extends "../base.html" %}
{% load static %}
{% block stylesheet %}{% static 'payment/css/payment.css' %}{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="login d-flex align-items-center">
    <div class="col-12 col-md-6  col-lg-6 mx-auto">
      {% block sub_content %}{% endblock %}
    </div>
  </div>
</div>
{% endblock %}